server:
  port: 8082

spring:
  application:
    name: notification-consumer-service
  zipkin:
    base-url: http://localhost:9411

aws:
  queue:
    name: ZIPKIN-TEST-QUEUE-2

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}