server:
  port: 8081

spring:
  application:
    name: delivery-service
  zipkin:
    base-url: http://localhost:9411

aws:
  queue:
    name: ZIPKIN-TEST-QUEUE-2

cloud:
  aws:
    region:
      static: ap-northeast-2
